# '''
# Author: Matthew Bandura
# Created on Wednesday 4th January, 13:26:17  
# '''

## grabs the number of SSSF buildings being remediated in ACM (generated by an R script)
import pandas as pd
import openpyxl

def generate_social_misc(MI_tables):
    #UPDATE AUTOMATICALLY
    MI_wb = openpyxl.load_workbook(MI_tables)
    Social_misc = MI_wb['Social_misc']

    SSSF_ACM = Social_misc['A2'].value

    social_misc = pd.DataFrame({f'SSSF in ACM': [SSSF_ACM]})
    MI_wb.close()

    return social_misc

    